Controller fmu
twiinIT/rocket-twin pull request #14
Opened 2023-07-06 12:53 UTC by luca7084

Added fmu controller, to be worked upon in regards to modularity. Needs cosapp_fmu to be installed manually since the right input for requirements.txt was not found (yet).

2023-07-06 16:21 UTC, GuyDSP requested changes

2023-07-06 16:21 UTC, GuyDSP commented on rocket_twin/systems/control/clock.py
why don't you directly use self.time ? 
we need to find a way to avoid this clock system ...

2023-07-06 16:21 UTC, GuyDSP commented
could you ask Adrien to help us on these 2 failing commit checks ?

2023-07-07 07:47 UTC, luca7084 commented on rocket_twin/systems/control/clock.py
Cosapp currently doesn't recognize the OpenModelica variable 'time' as the FMUSystem's self.time. I also can't declare a time variable in the beginning of the OpenModelica code, because it would be added to the FMUSystem as an inward. The only solution I found was to pass the time as another variable from a specialized system

2023-07-11 11:40 UTC, luca7084 commented on rocket_twin/systems/control/clock.py
Solved

2023-07-12 16:19 UTC, GuyDSP requested changes

2023-07-12 16:19 UTC, GuyDSP commented on rocket_twin/systems/control/__init__.py
"controler" is better than "controller" in this context

2023-07-12 16:19 UTC, GuyDSP commented on rocket_twin/systems/control/controller.py
> +class Controller(System):
ControlerFMU is a better name ?

2023-07-12 16:19 UTC, GuyDSP commented on rocket_twin/systems/control/cosapp_controller.py
> +class CosappController(System):
ControlerCoSApp ? at least consistant with ControlerFMU ?

2023-07-12 16:19 UTC, GuyDSP commented on rocket_twin/systems/station/station.py
> +        the .fmu file name
obsolet

2023-07-12 16:19 UTC, GuyDSP commented on rocket_twin/utils/create_fmu.py
could be a function added to the ControlerFMU class ?

2023-07-13 07:40 UTC, luca7084 commented on rocket_twin/systems/station/station.py
> +        the .fmu file name
Check

2023-07-13 07:46 UTC, luca7084 commented on rocket_twin/systems/control/controller.py
> +class Controller(System):
Check

2023-07-13 07:46 UTC, luca7084 commented on rocket_twin/systems/control/cosapp_controller.py
> +class CosappController(System):
Check

2023-07-13 09:37 UTC, luca7084 commented on rocket_twin/systems/control/__init__.py
What is the difference?

2023-07-13 09:37 UTC, adriendelsalle commented on .github/workflows/commit-verification.yml
@GuyDSP this is the CI workflow definition

2023-07-13 09:43 UTC, adriendelsalle reviewed
Many changes are not related to adding an FMU controller
it makes the PR touching a lot of files

you should probably split this PR in pieces:
- add a new system and its unit tests
- add a PR for each level of integration in aggregates systems + tests

2023-07-13 09:43 UTC, adriendelsalle commented on rocket_twin/systems/engine/engine.py
not related to adding an FMU controller

2023-07-13 09:46 UTC, adriendelsalle commented on rocket_twin/systems/engine/engine.py
or rename the PR `Add control to rocket and ground station` and more details about whats changes were introduced in this context in the PR description?

2023-07-13 10:47 UTC, luca7084 commented on rocket_twin/utils/create_fmu.py
Check

2023-07-13 10:49 UTC, luca7084 commented on rocket_twin/systems/engine/engine.py
Changed the description and the PR name. Should I split the PR anyway?

2023-07-17 10:30 UTC, GuyDSP approved these changes

2023-07-17 11:38 UTC, merged