Two stages
twiinIT/rocket-twin pull request #19
Opened 2023-07-24 11:51 UTC by luca7084

Proposal for a stage class

2023-07-24 12:59 UTC, GuyDSP requested changes

2023-07-24 12:59 UTC, GuyDSP commented on .pre-commit-config.yaml
do you need to set the version ? or just take the mast one is enough ?

2023-07-24 13:30 UTC, luca7084 commented on .pre-commit-config.yaml
I just changed the version, it was set to 0.5.0. It was Adrien who set it.

2023-07-25 11:47 UTC, GuyDSP approved these changes

2023-07-25 11:48 UTC, GuyDSP commented
Ok for me. Thanks

2023-07-25 11:49 UTC, merged